version: '3.8'

services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - portfolio-data:/var/data
      - portfolio-storage:/var/data/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/data/database.sqlite
      - LARAVEL_STORAGE_PATH=/var/data/storage
      - LOG_CHANNEL=stdout
      - PORT=80
      - JWT_SECRET=9d76efb690e79569f21688b28e61b847fd0dd76a78b63a08203863d20cf8d245
      - APP_KEY=base64:FRS7TFF32X0A/rRtsIV+LkUJwk7avm+mxNv9LNdIAbw=
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - portfolio-network
    restart: unless-stopped

volumes:
  portfolio-data:
    driver: local
  portfolio-storage:
    driver: local

networks:
  portfolio-network:
    driver: bridge